### PR TITLE
ENH: add the TotalSegmentator roi_subset option

### PR DESCRIPTION
**Pull request by rbumm**
- choose organ/structure from a sorted QListWidget
- multilselect is possible

### CODE REVIEW

**Comment by lassoan** [comment]
Thanks for working on this. Unfortunately, there might be some misunderstanding about how the selective segment saving can be utilized. 

The reason for development of selective saving feature was to make pre-segmentation faster. Pre-segmentation is required for some tasks to get bounding box for a region. The pre-segmentation performs the total-fast task with individual segment saving, which produces 104 segments and takes a very long time to save. In these cases, we can make the pre-segmentation fater by saving only the single segment that the main segmentation task needs. This pre-segmentation segment is a hardcoded value that we can store in the logic.tasks map. We don't need to add GUI for this: it is just an under-the-hood change that makes certain segmentation tasks a bit faster, without introducing any additional complexity. 

This pull request adds GUI for segment selection. What is the motivation for selecting segments manually? Loading a single segment takes the same amount of time as loading all segments from a multilabel segmentation. Therefore, performance gain is only possible for those tasks that do not support multilabel saving, but those only have a few segments, so the speed improvement is negligible. Manual segment selection would make the module more complex to use (and therefore explain and support) and maintain. Does the current implementation store the segment selection in the scene? Does the segment list show the segments provided by the selected task? If not, then we would need to implement these, too. Overall, I'm not sure if all the future effort of implementation, documentation, maintenance, support and instead GUI complexity for users is worth it, if all we can gain is up to a few percent shorter processing time.

**Comment by rbumm** [comment]
Thank you for your comments. I think implementing this in the GUI would be helpful because many users would just focus on 3-5 organs/structures of interest when using TS. Ideally, you would want to be able to save your selection of choice for future use. It is very helpful to have the roi\_subset option in the logic when I call the logic from Lung CT segmenter, because it saves nearly a minute of saving time (I could just ask for lobes and airways). 

I agree that implementing a UI would be more complicated, so we could skip that for the moment or hide it in a collapsible button. Maybe discuss that with @pieper?

**Comment by lassoan** [comment]
Which task and what segments are you using?

**Comment by rbumm** [comment]
Just the normal TotalSegmentation with -i and -o, only lung\_vessel upon request

**Comment by lassoan** [comment]
I see, so you use the "total" task (that's the default task). How long does the full processing take if you specify the segment (so multilabel option is used) and how long does it take if you don't specify a segment (and so multilabel is used and you got all the segments)?

**Comment by rbumm** [comment]
Actually, tested this with

```

python .\TotalSegmentator -i "C:\Users\rudol\input.nii.gz" -o "C:\Users\rudol\segmentation"

```



vs

```

python .\TotalSegmentator -i "C:\Users\rudol\input.nii.gz" -o "C:\Users\rudol\segmentation" --task total --roi_subset lung_upper_lobe_right lung_middle_lobe_right lung_lower_lobe_right
```



only from the windows command line.

**Comment by lassoan** [comment]
In full-resolution mode SlicerTotalSegmentator always saves the 104 segments in multilabel mode (`--ml`), which takes 0.59s. Therefore the 6.50s saving time is not an improvement but a slowdown, and if we also take into account the loading time then the slowdown is increased even more.

How `--roi_subset` can speeed up things instead of slowing down:
- 1. Pre-segmentation: for pre-segmentation we cannot use `--ml` anyway and we only need a single segment. Very easy, no GUI change is needed. Reduces total segmentation time for tasks that need pre-segmentation by about 1 minute (on my computer saving all segments take 80s, while saving one segment takes about a second).
- 2. Full-resolution segmentation: if TotalSegmentator only runs those models that are specified in the list then instead of running 5 segmentation tasks, we only need to run 1 or a few. This needs a little development in TotalSegmentator (see [this comment](https://github.com/wasserth/TotalSegmentator/blob/master/bin/TotalSegmentator#L55)) and it would need some further development in this extension (save/load list of ROIs in the parameter node in the scene, show segment list relevant for the selected segmentation task, add search&filter, clear all, select all, etc. options to make selection in the very long segment list feasible, etc.)

I think we should first implement (1) as it is very easy to do. Then, while we are waiting for Jakob to implement selective running of models, we could implement the required further improvements to the extension. You could also help out Jakob with implementing the selective running of models.

**Pull request closed without merging**
