### PR TITLE
Total segmentatorv2

### PR DESCRIPTION
**Pull request by lassoan**
Update the Slicer module to use TotalSegmentator v2.x

@rbumm I've accidentally closed [your TotalSegmentator v2 pull request](https://github.com/lassoan/SlicerTotalSegmentator/pull/32) and cannot reopen it. So, I've created a new one from the same branch content. Please test.

Remaining tasks:
- [x] Update TotalSegmentator to a new version that contains the [fix for the redownloading of fast weights](https://github.com/wasserth/TotalSegmentator/pull/202)
- [x] Update TotalSegmentator to a new version that contains a fix for [the whole around the heart issue](https://github.com/wasserth/TotalSegmentator/issues/194)
- [ ] Get confirmation from @fedorov that the terminology mapping csv and terminology json are reasonable
- [x] Get confirmation from @rbumm that installation is robust (SimpleITK is not reinstalled)

### CODE REVIEW

**Comment by fedorov** [comment]
> Get confirmation from @fedorov that the terminology mapping csv and terminology json are reasonable

I started working on this. The mapping will definitely need to be fixed for some terms.

**Comment by rbumm** [comment]
To be able to work on this, I forked the whole project again including the v2 branch. 
This was prpobably wrong. What should I have been doing instead ? 
Good news is that before the Bump to 2.0.5 TS and lungmask worked both fine, no SimpleITK issues.

**Comment by lassoan** [comment]
No need to fork the project again.

The simplest is to just use the "propose change" option in the code review comment. To suggest small changes.

If you want to propose substantial changes (many places or multiple files) then you can use GitHub's web interface to modify files in this branch. Github will offer to create a branch and create a pull request. Accept those and then you'll have your branch. You can then make any changes in that branch because it is in your own fork. Then I can merge those changes into my branch.

**Comment by lassoan** [comment]
> I started working on this. The mapping will definitely need to be fixed for some terms.

Thanks a lot @fedorov!

It is really interesting to see how useful these codes can be. For example, it seems that different people want to use different English names for the same things. By relying on standard codes, we can let everyone to use whatever name they prefer, yet allow computational algorithms to accurately interpret the data, automatically harmonize nomenclature, etc.

**Comment by fedorov** [comment]
I have the current changes so far here: https://docs.google.com/spreadsheets/d/1aeTGUjZJNxw6fd2Mu0L32m8KP2suky5iboQ8M4ocfqM/edit#gid=844414326. 

First sheet contains new codes for v2, and those in orange modified by me.

Second sheet contains v1 codes.

Third sheet is automatically generated, and contains only those structures that are new in v2 (just for convenience).

I am almost done, and also reviewed these revisions with @dclunie. I am waiting to clarify one issue and have the final review by David, and once finalized I will submit a PR.

**Comment by fedorov** [comment]
@lassoan note that because (what a weird decision) there is a separate code for cyst in left and right kidney, the CSV now will have 3 new columns to introduce AnatomicRegionModifierSequence, which will have repercussions on the parser and the code propagating those attributes through the data structures.

**Comment by lassoan** [comment]
Everything seems to work well now.

@rbumm please test the installation. If everything goes well then we can merge this.

@fedorov feel free to send a pull request with terminology fixes whenever you are ready.

**Comment by rbumm** [comment]
I have tested the installation, everything works fine. The holes in FAST mode are gone, downloads are only done once and the licensing mechanism works. 
Appendicular bones produced a good segmentation resullt but the following messages:  
````
Saving segmentations...
  Saved in 1.37s
Importing segmentation results...
Failed to deserialize terminology string: Segmentation category and type - DICOM master list~SCT^123037004^Anatomical Structure~SCT^23416004^Ulna~^^~Anatomic codes - DICOM master list~^^~^^|
Failed to deserialize terminology string: Segmentation category and type - DICOM master list~SCT^123037004^Anatomical Structure~SCT^62413002^Radius~^^~Anatomic codes - DICOM master list~^^~^^|
Failed to deserialize terminology string: Segmentation category and type - DICOM master list~SCT^123037004^Anatomical Structure~SCT^83936004^Carpus~^^~Anatomic codes - DICOM master list~^^~^^|
Failed to deserialize terminology string: Segmentation category and type - DICOM master list~SCT^123037004^Anatomical Structure~SCT^36455000^Metacarpal bones~^^~Anatomic codes - DICOM master list~^^~^^|
Failed to deserialize terminology string: Segmentation category and type - DICOM master list~SCT^123037004^Anatomical Structure~SCT^28641004^Phalanx structure~^^~Anatomic codes - DICOM master list~^^~^^|
Cleaning up temporary folder...
Processing completed in 566.60 seconds

Processing finished.
````
The initial download for the "total" task in non-fast mode can be very long, maybe a message would be good. 
lungmask is working, so the SimpeITK problem is solved.  

Excellent work!

**Comment by fedorov** [comment]
@lassoan I see that the terminology you are using includes the structures that are covered by a restrictive license (the below is from https://github.com/wasserth/TotalSegmentator#subtasks. You are not including the model that generates those restrictively licensed items in Slicer, right?

image

**Comment by lassoan** [comment]
Thanks for the updates @fedorov
We'll support all models, so it would be great if you could add terminology items for all the structures. But the most important are the structures of the "total" task.

**Comment by fedorov** [comment]
I reviewed all of the structures that were on the list.

**Comment by lassoan** [comment]
@rbumm I see that you have changed the TotalSegmentator weights folder to be the scripts folder. This can be an issue, because it means that the weights are re-downloaded for each Slicer release, which may take a really long time and significant cost for some users; and it also takes up gigabytes of space for each Slicer release. Was there any specific reason for this? Was this needed for the license setting?

**Comment by rbumm** [comment]
> @rbumm I see that you have changed the TotalSegmentator weights folder to be the scripts folder. This can be an issue, because it means that the weights are re-downloaded for each Slicer release, which may take a really long time and significant cost for some users; and it also takes up gigabytes of space for each Slicer release. Was there any specific reason for this? Was this needed for the license setting?

This was just a Test in a moment when the weight download did not seem to work and was repetitive. Any other solution is welcome.

**Comment by rbumm** [comment]
It would be nice to be able to display the terminology upon checkbox action but this is probably too much.

**Comment by rbumm** [comment]
Just see that the name of the segment is displayed under "Data probe" which is already a good solution.

**Comment by lassoan** [comment]
I've tested this branch with latest Slicer Preview Release and fixed all the issues that I've found. I've now merged this branch into the main branch and updated the Slicer Extensions Index so that Slicer-5.4 still uses TotalSegmentator v1, while latest Slicer-5.5 will use TotalSegmentator v2. This was needed because Python packages in Slicer-5.5 were too new to be compatible with TotalSegmentator v1 dependencies.

**Pull request merged**
