### PR TITLE
fix snomed ct codes

### PR DESCRIPTION
**Pull request by vkt1414**
We found more closely related codes for some of the body parts.

### CODE REVIEW

**Review by lassoan — APPROVED** [review]
Thank you, it looks good (except the two typos). It is consistent with the mapping that is the TotalSegmentator repository (https://github.com/wasserth/TotalSegmentator/blob/master/resources/totalsegmentator_snomed_mapping.csv).

We'll soon switch to use the mapping in the TotalSegmentator repository, but until then this will work well.

**Comment by vkt1414** [comment]
> Thank you, it looks good (except the two typos). It is consistent with the mapping that is the TotalSegmentator repository (https://github.com/wasserth/TotalSegmentator/blob/master/resources/totalsegmentator_snomed_mapping.csv).
> 
> We'll soon switch to use the mapping in the TotalSegmentator repository, but until then this will work well.

Thanks! @lassoan for recognizing the two typos. I work in @fedorov lab and actually we were the ones who contributed the above the map to the TotalSegmentator repo. At some point in the future, we may update that map to include v2 also.

**Comment by lassoan** [comment]
Great!

@rbumm has already come up with [terminology entries for TotalSegmentator v2 segments](https://github.com/rbumm/SlicerTotalSegmentator/blob/TotalSegmentatorv2/TotalSegmentator/TotalSegmentator.py#L351), it would be great if you could review them and give any feedback in the [associated pull request](https://github.com/lassoan/SlicerTotalSegmentator/pull/32). Thank you!

**Comment by fedorov** [comment]
@lassoan thanks for letting us know about the above. There are some codes that definitely will require fixes. I will follow up in that PR.

**Pull request merged**
