### PR TITLE
BUG: fix codes for some terms in v2 terminology

### PR DESCRIPTION
**Pull request by fedorov**
Follow up on #38

It is easier to see the terms that were changed in this spreadsheet: https://docs.google.com/spreadsheets/d/1aeTGUjZJNxw6fd2Mu0L32m8KP2suky5iboQ8M4ocfqM/edit#gid=844414326 (sheet 1, highlighted).

Note that the mapping now contains 3 new columns: 

AnatomicRegionModifierSequence.CodingSchemeDesignator | AnatomicRegionModifierSequence.CodeValue | AnatomicRegionModifierSequence.CodeMeaning
-- | -- | --

It will be important to make sure those propagate when mapping is applied.

### CODE REVIEW

**Comment by lassoan** [comment]
Thanks a lot @fedorov this is great! I'll try to update the code today to use the anatomic region modifier columns as well.

**Comment by fedorov** [comment]
You are right - I missed it! It should be split to use the modifier. Will you fix it or should I send a PR?

**Comment by lassoan** [comment]
I'll fix it, just write me the correct code for "inferior" modifier. Thank you!

**Comment by lassoan** [comment]
@fedorov Sorry, a couple of more questions - just for my own education and so that I can give good advice to others.

1. Vena cava

What is the difference between the dedicated code ("inferior vena cava") and the generic+modifier code ("vena cava" + "inferior")?
Are they equivalent?
Is one of them a preferred code for medical image segmentation?
Is it documented somewhere?
Is there a mapping table that maps less preferred codes to equivalent more preferred codes?

These all are quite important because if there were several equivalent codes for the same thing even in the same coding scheme then that would kind of defeat the purpose of using a standard terminologies. It would not make standard terminologies entirely useless, but we would need some software solutions to deal with the resulting redundancies/inconsistencies.

2. Costal cartilage

Do you know the difference between these?
- `50016007` [Structure of costal cartilage](https://www.findacode.com/snomed/50016007--structure-of-costal-cartilage.html)
- `244703004` [Entire costal cartilage](https://www.findacode.com/snomed/244703004--entire-costal-cartilage.html)

Why 244703004 (which is the child of 50016007) is better?
Is it documented somewhere that one is appropriate for image segmentation and other is not?

DICOM terminology in Slicer uses 50016007. Should we change that, too (and all similar cases when the "structure of..." code is used instead of "entire..." code)?

**Comment by fedorov** [comment]
Actually, I am not sure anymore which approach is preferred. I thought the logic is always to factor our those modifiers, as documented in but the DICOM table here does not: https://dicom.nema.org/medical/dicom/current/output/chtml/part16/sect_CID_6117.html. At the same time, it did happen in the past that code selection in DICOM was not correct. I am waiting to hear back from @dclunie about this.

Now that I look again, I see there may be some more refinements. I will send another PR. I am sorry for not doing it right on the first try...

**Comment by lassoan** [comment]
Thanks a lot, I'm looking forward to the new PR then.

The links you provided are very useful, but I wouldn't have even thought that I could find such useful notes in the DICOM standard. It would help with the adoption of terminologies if there was a simple tutorial that would explain to developers the general process and tips&tricks for determining the correct code, heavily referencing the DICOM standard.

**Comment by dclunie** [comment]
Wrt. codes in CID 6117, these were originally introduced in the standard for use in an SR template ([TID 4104](https://dicom.nema.org/medical/dicom/current/output/chtml/part16/sect_TID_4104.html) for Chest CAD, Row 2) where the anatomy itself was a potential modifier of a finding, and so there was not an option for post-coordinating these (a single concept was needed to fully convey the location). In a segmentation context, we have more flexibility, so I would not read too much into these.

In general, the subject of pre-coordination vs. post-coordination has been the subject of religious wars, and we try to take a pragmatic path. In particular, we do not used so-called "post-coordinated expressions" in SNOMED CT, if for no other reasons than that creates an unbounded space for matching and is SNOMED-specific when we use other coding schemes. Any post-coordination in DICOM has to be done with explicit modifier attributes or content items. There is a body of literature on the theoretical and practical aspects of this if you want some references to research; [this](https://archive.nyu.edu/bitstream/2451/14173/1/IS-97-14.pdf) is a good general start and [this](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2244193/) and [this](https://academic.oup.com/jamia/article-lookup/doi/10.1136/amiajnl-2013-002456) are SNOMED specific.

There is no right or wrong answer for many of these choices, but generally for a particular application, I try to maintain internal consistency within the sub-set of concepts selected for that use case (within reason).

As for entire vs. structure of, if you want to go down this rabbit hole, search for the philosophical topic of "[mereology](https://en.wikipedia.org/wiki/Mereology)" (the study of wholes vs. parts and their relations). We are talking Plato/Aristotle here. The SNOMED folks believe in that religion, other ontologies don't. Generally in imaging we are trying to say "this is in the liver" not "this is the entire liver, no more and no less", and we are not trying to distinguish when we are doing one or the other or relate the two (one notable exception in DICOM being "entire body", for which I or someone else dubiously used the "[entire body](http://snomed.info/id/38266002)" SNOMED code, even though we know, e.g., a whole body PET doesn't always include the toes, but since the word "entire" or "whole" was used in the code meaning ... in short we almost always use "structure of" and almost never "entire" and this has been [documented in the standard](https://dicom.nema.org/medical/dicom/current/output/chtml/part16/chapter_8.html#sect_8.1.1) for a while now and updates have been made to assure this.

If I could have written a "simple" tutorial about this, I probably would have, since Andrey has been trying to convince me to do that since the beginning of the QIICR project. At that time, he made a nice [Searching for codes outside DICOM](https://qiicr.gitbook.io/dcmqi-guide/opening/coding_schemes/searching_codes_outside_dicom) page, but that doesn't really cover the subtlety of anatomy modifiers. We were also working at the time on brain tumor lesion types as discussed in the [CP 1849](https://dicom.nema.org/medical/dicom/Final/cp1849_ft_braintumorsegmentationcodes.pdf) do I described more of my rational at the time, but I don't think Andrey was impressed.

**Comment by dclunie** [comment]
PS. If you think selecting codes is hard, try defining them - see, for example, this diatribe on [what the "abdomen" is in SNOMED CT](http://dx.doi.org/10.1111/joa.13384).

This paper is actually relevant in the general context of segmenting the body (but AFAIK you are not defining regions, only parts such as organs within these regions, so that probably doesn't apply to your code table for now).

**Comment by dclunie** [comment]
Since you mentioned SVC and IVC earlier, I wrote to Andrey earlier:

"Since these are such distinct structures In their own region, I would probably pre-coordinate these (not use a superior/inferior modifier), just as, for example, I would almost always pre-coordinate left/right ventricle, etc. in the heart."

But reiterate that this is a judgment call and there is no correct answer.

**Comment by dclunie** [comment]
Likewise, if you were segmentating "aorta" into its distinct parts (which AFAIK you are not), I would probably recommend pre-coordinate "ascending aorta", "arch of aorta", "descending aorta" (or combine them as "thoracic aorta") and distinguish them from "abdominal aorta", rather than attempting to use modifiers.

**Comment by fedorov** [comment]
> in short we almost always use "structure of" and almost never "entire"

@dclunie for the metatarsal, there is no code that specifically starts from "structure of". There's "Entire" one (which we should not use): http://snomed.info/id/302532000, and then there is the parent of it that is "Metatarsal bone structure (body structure)" http://snomed.info/id/53884002. We should use the latter, correct? If yes, would it be correct to define a rule such as "if you see code that starts from "entire", use its parent instead, even if it does not start with "the structure of""?

**Comment by dclunie** [comment]
It is quite common for SNOMED concepts that are structures not to have a name that begins with 'structure of" but rather to end with 'structure" or some other pattern, as you have discovered.

Working back from "entire" is a good idea, but should not be used blindly - read the FSN and synonyms of the parent and understand them and see if they makes sense, also exploring siblings and more parents if necessary.

Cross-referencing to UMLS is also a good idea (enter the code at the [UMLS site ](https://uts.nlm.nih.gov/uts/umls/home) and see what it maps to in other schemes, or indeed start from there). E.g., see [metatarsal in UMLS](https://uts.nlm.nih.gov/uts/umls/concept/C0025584). And/or [metatarsal in Bioportal](https://bioportal.bioontology.org/search?q=metatarsal).

PS. Yes, use [SCT:53884002](http://snomed.info/id/53884002) if you want to refer to any one of those bones, and not a particular metatarsal, and not the region of the foot that contains the metatarsals, or the set of all of the metatarsals, etc.

Note that in DICOM PS3.16 we refer to the metatarsus as an anatomic region, so use [SCT:280711000 "Structure of region of metatarsal (body structure)"](http://snomed.info/id/280711000) for that (not that we wouldn't use 53884002 if/when we wanted to refer to one of the bones themselves). We are probably not terribly consistent about that, and there are not corresponding "region" concepts for every anatomic structure in SNOMED CT AFAIK.

**Comment by lassoan** [comment]
Thank you for all the very interesting information. I'm learning a lot!

**Pull request merged**
