### PR TITLE
Bump to TS 2.0.5

### PR DESCRIPTION
**Pull request by rbumm**

### CODE REVIEW

**Comment by rbumm** [comment]
Bumping to 2.0.5 results in error messages: 

Processing started
Writing input file to C:/Users/Rudolf/AppData/Local/Temp/Slicer/__SlicerTemp__2023-10-20_15+17+00.790/total-segmentator-input.nii
Creating segmentations with TotalSegmentator AI...
Total Segmentator arguments: ['-i', 'C:/Users/Rudolf/AppData/Local/Temp/Slicer/__SlicerTemp__2023-10-20_15+17+00.790/total-segmentator-input.nii', '-o', 'C:/Users/Rudolf/AppData/Local/Temp/Slicer/__SlicerTemp__2023-10-20_15+17+00.790/segmentation', '--ml', '--task', 'total', '--fast']
Traceback (most recent call last):
  File "C:\Users\Rudolf\AppData\Local\slicer.org\Slicer 5.4.0_2\lib\Python\Lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Rudolf\AppData\Local\slicer.org\Slicer 5.4.0_2\lib\Python\Lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Rudolf\AppData\Local\slicer.org\Slicer 5.4.0_2\lib\Python\Scripts\TotalSegmentator.exe\__main__.py", line 7, in <module>
  File "C:\Users\Rudolf\AppData\Local\slicer.org\Slicer 5.4.0_2\lib\Python\Lib\site-packages\totalsegmentator\bin\TotalSegmentator.py", line 127, in main
    totalsegmentator(args.input, args.output, args.ml, args.nr_thr_resamp, args.nr_thr_saving,
  File "C:\Users\Rudolf\AppData\Local\slicer.org\Slicer 5.4.0_2\lib\Python\Lib\site-packages\totalsegmentator\python_api.py", line 77, in totalsegmentator
    from totalsegmentator.nnunet import nnUNet_predict_image  # this has to be after setting new env vars
  File "C:\Users\Rudolf\AppData\Local\slicer.org\Slicer 5.4.0_2\lib\Python\Lib\site-packages\totalsegmentator\nnunet.py", line 23, in <module>
    from nnunetv2.inference.predict_from_raw_data import predict_from_raw_data
ImportError: cannot import name 'predict_from_raw_data' from 'nnunetv2.inference.predict_from_raw_data' (C:\Users\Rudolf\AppData\Local\slicer.org\Slicer 5.4.0_2\lib\Python\Lib\site-packages\nnunetv2\inference\predict_from_raw_data.py)
Exception ignored in: <totalsegmentator.libs.DummyFile object at 0x000002AA56F228E0>
AttributeError: 'DummyFile' object has no attribute 'flush'

**Comment by lassoan** [comment]
> ImportError: cannot import name 'predict_from_raw_data' from
'nnunetv2.inference.predict_from_raw_data' (C:\Users\Rudolf\AppData\Local\
slicer.org\Slicer
5.4.0_2\lib\Python\Lib\site-packages\nnunetv2\inference\predict_from_raw_data.py)

This seems like an issue in TotalSegmentator: it is not compatible with the nnunetv2 version.

It is our fault, as we have hardcoded nnunetv2 version in our installation script (`self.pipInstallSelective('nnunetv2', "nnunetv2==2.2", packagesToSkip)`). Instead, we should get the correct version from TotalSegmentator dependencies. For now, we could just change `2.2` to `2.1` (in accordance with the [current requirement](https://github.com/wasserth/TotalSegmentator/blob/2b46907bbec41ece2b69cde52f8741966675485b/setup.py#L34)).

**Comment by rbumm** [comment]
Will it make sense to commit to this PR or will I have to wait for changes in the other PR ?

**Review by lassoan — APPROVED** [review]
Thank you!

I'll also have to update nnunetv2 version (downgrade to 2.1, as 2.2 caused the big hole around the heart)

**Pull request merged**
